# CMAKE generated file: DO NOT EDIT!
# Generated by "NMake Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

!IF "$(OS)" == "Windows_NT"
NULL=
!ELSE
NULL=nul
!ENDIF
SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Git\orderBook

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Git\orderBook\cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache\fast: edit_cache

.PHONY : edit_cache\fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	echo >nul && "C:\Program Files\JetBrains\CLion 2020.1\bin\cmake\win\bin\cmake.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache\fast: rebuild_cache

.PHONY : rebuild_cache\fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Git\orderBook\cmake-build-debug\CMakeFiles C:\Git\orderBook\cmake-build-debug\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Git\orderBook\cmake-build-debug\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) clean
.PHONY : clean

# The main clean target
clean\fast: clean

.PHONY : clean\fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall\fast:
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) preinstall
.PHONY : preinstall\fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named orderBook

# Build rule for target.
orderBook: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 /nologo -$(MAKEFLAGS) orderBook
.PHONY : orderBook

# fast build rule for target.
orderBook\fast:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\build
.PHONY : orderBook\fast

Commands\MdReplay.obj: Commands\MdReplay.cpp.obj

.PHONY : Commands\MdReplay.obj

# target to build an object file
Commands\MdReplay.cpp.obj:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Commands\MdReplay.cpp.obj
.PHONY : Commands\MdReplay.cpp.obj

Commands\MdReplay.i: Commands\MdReplay.cpp.i

.PHONY : Commands\MdReplay.i

# target to preprocess a source file
Commands\MdReplay.cpp.i:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Commands\MdReplay.cpp.i
.PHONY : Commands\MdReplay.cpp.i

Commands\MdReplay.s: Commands\MdReplay.cpp.s

.PHONY : Commands\MdReplay.s

# target to generate assembly for a file
Commands\MdReplay.cpp.s:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Commands\MdReplay.cpp.s
.PHONY : Commands\MdReplay.cpp.s

Commands\ModifyOrder.obj: Commands\ModifyOrder.cpp.obj

.PHONY : Commands\ModifyOrder.obj

# target to build an object file
Commands\ModifyOrder.cpp.obj:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Commands\ModifyOrder.cpp.obj
.PHONY : Commands\ModifyOrder.cpp.obj

Commands\ModifyOrder.i: Commands\ModifyOrder.cpp.i

.PHONY : Commands\ModifyOrder.i

# target to preprocess a source file
Commands\ModifyOrder.cpp.i:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Commands\ModifyOrder.cpp.i
.PHONY : Commands\ModifyOrder.cpp.i

Commands\ModifyOrder.s: Commands\ModifyOrder.cpp.s

.PHONY : Commands\ModifyOrder.s

# target to generate assembly for a file
Commands\ModifyOrder.cpp.s:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Commands\ModifyOrder.cpp.s
.PHONY : Commands\ModifyOrder.cpp.s

Commands\Subscribes.obj: Commands\Subscribes.cpp.obj

.PHONY : Commands\Subscribes.obj

# target to build an object file
Commands\Subscribes.cpp.obj:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Commands\Subscribes.cpp.obj
.PHONY : Commands\Subscribes.cpp.obj

Commands\Subscribes.i: Commands\Subscribes.cpp.i

.PHONY : Commands\Subscribes.i

# target to preprocess a source file
Commands\Subscribes.cpp.i:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Commands\Subscribes.cpp.i
.PHONY : Commands\Subscribes.cpp.i

Commands\Subscribes.s: Commands\Subscribes.cpp.s

.PHONY : Commands\Subscribes.s

# target to generate assembly for a file
Commands\Subscribes.cpp.s:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Commands\Subscribes.cpp.s
.PHONY : Commands\Subscribes.cpp.s

Parser\CommandsParser.obj: Parser\CommandsParser.cpp.obj

.PHONY : Parser\CommandsParser.obj

# target to build an object file
Parser\CommandsParser.cpp.obj:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Parser\CommandsParser.cpp.obj
.PHONY : Parser\CommandsParser.cpp.obj

Parser\CommandsParser.i: Parser\CommandsParser.cpp.i

.PHONY : Parser\CommandsParser.i

# target to preprocess a source file
Parser\CommandsParser.cpp.i:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Parser\CommandsParser.cpp.i
.PHONY : Parser\CommandsParser.cpp.i

Parser\CommandsParser.s: Parser\CommandsParser.cpp.s

.PHONY : Parser\CommandsParser.s

# target to generate assembly for a file
Parser\CommandsParser.cpp.s:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Parser\CommandsParser.cpp.s
.PHONY : Parser\CommandsParser.cpp.s

Storage\Storage.obj: Storage\Storage.cpp.obj

.PHONY : Storage\Storage.obj

# target to build an object file
Storage\Storage.cpp.obj:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Storage\Storage.cpp.obj
.PHONY : Storage\Storage.cpp.obj

Storage\Storage.i: Storage\Storage.cpp.i

.PHONY : Storage\Storage.i

# target to preprocess a source file
Storage\Storage.cpp.i:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Storage\Storage.cpp.i
.PHONY : Storage\Storage.cpp.i

Storage\Storage.s: Storage\Storage.cpp.s

.PHONY : Storage\Storage.s

# target to generate assembly for a file
Storage\Storage.cpp.s:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\Storage\Storage.cpp.s
.PHONY : Storage\Storage.cpp.s

View\Menu.obj: View\Menu.cpp.obj

.PHONY : View\Menu.obj

# target to build an object file
View\Menu.cpp.obj:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\Menu.cpp.obj
.PHONY : View\Menu.cpp.obj

View\Menu.i: View\Menu.cpp.i

.PHONY : View\Menu.i

# target to preprocess a source file
View\Menu.cpp.i:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\Menu.cpp.i
.PHONY : View\Menu.cpp.i

View\Menu.s: View\Menu.cpp.s

.PHONY : View\Menu.s

# target to generate assembly for a file
View\Menu.cpp.s:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\Menu.cpp.s
.PHONY : View\Menu.cpp.s

View\Print.obj: View\Print.cpp.obj

.PHONY : View\Print.obj

# target to build an object file
View\Print.cpp.obj:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\Print.cpp.obj
.PHONY : View\Print.cpp.obj

View\Print.i: View\Print.cpp.i

.PHONY : View\Print.i

# target to preprocess a source file
View\Print.cpp.i:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\Print.cpp.i
.PHONY : View\Print.cpp.i

View\Print.s: View\Print.cpp.s

.PHONY : View\Print.s

# target to generate assembly for a file
View\Print.cpp.s:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\Print.cpp.s
.PHONY : View\Print.cpp.s

View\PrintFull.obj: View\PrintFull.cpp.obj

.PHONY : View\PrintFull.obj

# target to build an object file
View\PrintFull.cpp.obj:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\PrintFull.cpp.obj
.PHONY : View\PrintFull.cpp.obj

View\PrintFull.i: View\PrintFull.cpp.i

.PHONY : View\PrintFull.i

# target to preprocess a source file
View\PrintFull.cpp.i:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\PrintFull.cpp.i
.PHONY : View\PrintFull.cpp.i

View\PrintFull.s: View\PrintFull.cpp.s

.PHONY : View\PrintFull.s

# target to generate assembly for a file
View\PrintFull.cpp.s:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\PrintFull.cpp.s
.PHONY : View\PrintFull.cpp.s

View\SubscribesView.obj: View\SubscribesView.cpp.obj

.PHONY : View\SubscribesView.obj

# target to build an object file
View\SubscribesView.cpp.obj:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\SubscribesView.cpp.obj
.PHONY : View\SubscribesView.cpp.obj

View\SubscribesView.i: View\SubscribesView.cpp.i

.PHONY : View\SubscribesView.i

# target to preprocess a source file
View\SubscribesView.cpp.i:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\SubscribesView.cpp.i
.PHONY : View\SubscribesView.cpp.i

View\SubscribesView.s: View\SubscribesView.cpp.s

.PHONY : View\SubscribesView.s

# target to generate assembly for a file
View\SubscribesView.cpp.s:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\View\SubscribesView.cpp.s
.PHONY : View\SubscribesView.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles\orderBook.dir\build.make /nologo -$(MAKEFLAGS) CMakeFiles\orderBook.dir\main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... orderBook
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Commands/MdReplay.obj
	@echo ... Commands/MdReplay.i
	@echo ... Commands/MdReplay.s
	@echo ... Commands/ModifyOrder.obj
	@echo ... Commands/ModifyOrder.i
	@echo ... Commands/ModifyOrder.s
	@echo ... Commands/Subscribes.obj
	@echo ... Commands/Subscribes.i
	@echo ... Commands/Subscribes.s
	@echo ... Parser/CommandsParser.obj
	@echo ... Parser/CommandsParser.i
	@echo ... Parser/CommandsParser.s
	@echo ... Storage/Storage.obj
	@echo ... Storage/Storage.i
	@echo ... Storage/Storage.s
	@echo ... View/Menu.obj
	@echo ... View/Menu.i
	@echo ... View/Menu.s
	@echo ... View/Print.obj
	@echo ... View/Print.i
	@echo ... View/Print.s
	@echo ... View/PrintFull.obj
	@echo ... View/PrintFull.i
	@echo ... View/PrintFull.s
	@echo ... View/SubscribesView.obj
	@echo ... View/SubscribesView.i
	@echo ... View/SubscribesView.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

